# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
    - sdk/azidentity/

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
    - sdk/azidentity/

stages:
- template: /eng/pipelines/templates/jobs/archetype-sdk-client.yml
  parameters:
    RunLiveTests: true
    UsePipelineProxy: false
    ServiceDirectory: 'azidentity'
    CloudConfig:
      Public:
        SubscriptionConfigurations:
          - $(sub-config-azure-cloud-test-resources)
          # Contains alternate tenant, AAD app and cert info for testing
          - $(sub-config-identity-test-resources)
    ${{ if endsWith(variables['Build.DefinitionName'], 'weekly') }}:
      AdditionalMatrixConfigs:
        - Name: managed_identity_matrix
          Path: sdk/azidentity/platform-matrix.json
          Selection: sparse
          GenerateVMJobs: true
